apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: java-demo

  template:
    metadata:
      labels:
        app: java-demo

    spec:
      containers:
      - name: java-demo

        image: 976118139365.dkr.ecr.ap-south-1.amazonaws.com/java-demo:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080
